import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Amnesia.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class Amnesia extends Agent {
	/** */
	public void causeEffect(List<Virologist> targets, Virologist source) {
	}
	
	/** */
	public void step() {
	}
}
