//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bag.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** 
 * A zsák felszerelést reprezentálja. 
 * Használatával megnövekszik a virológus maximális anyag és maximális ágens kapacitása.
 * */

public class Bag extends Gear {
	private String name;
	
	/** 
	 * A konstruktor beállítja az objektum nevét, csak tesztelési célra.
	 * */
	
	public Bag(String _name) {
		name = _name;
	}
	
	/** 
	 * A védőfelszerelés speciális függvénye amely segítségével támadás esetén aktiválódik a 
	 * felszerelés hatása a virológuson. Ez a függvény a Bag esetében nem csinál semmit, 
	 * mindig false értékkel tér vissza.
	 * */
	
	public boolean specialEffect(Virologist v, Virologist att, Agent a) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".specialEffect()");
		
    	System.out.println(main.printIndentation() + "<-false");
		main.decreaseIndentation();
		return false;
	}
	
	/** 
	 * A védőfelszerelések felvételénél kifejtik hatásukat a virológusra. 
	 * Felvételkor meghívja a virológus setMaxMaterials és setMaxAgents függvényét, 
	 * ezzel beállítva a maximum anyag és maximum ágens megfelelő értékét.
	 * */
	
	public void onPickup(Virologist v) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".onPickup()");
		v.addGear(this);
		v.setMaxMaterials(15);
		v.setMaxAgents(5);
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** 
	 * A védőfelszerelések elvesztésekor a virológus is elveszíti a felvételkor szerzett hatásokat. 
	 * Meghívja a virológus setMaxMaterials és setMaxAgents függvényét, 
	 * ezzel visszaállítva a maximum anyag és maximum ágens értékét az eredeti értékre.
	 * */
	
	public void onLoss(Virologist v) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".onLoss()");
		v.setMaxMaterials(5);
		v.setMaxAgents(2);
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
}
