//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : C.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class C extends GeneticCode {
    public C() {requiredNucleotid = 1; requiredAminoacid = 2; agent = new Chorea("c"); name = "C";}
}
