import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Chorea.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class Chorea extends Agent {
	/** */
	public void causeEffect(List<Virologist> targets, Virologist source) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->causeEffect()");
		
		for(int i=0;i<targets.size();i++) {
			Virologist t = targets.get(i);
			if(t.infect(this, source)) {
				t.setChorea(true);
			}
		}
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** */
	public void step() {
	}

}
