import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class Field {
	/** */
	private Field neighbours;
	
	/** */
	protected Virologist virologists;
	
	/** */
	public void interact(Virologist v) {
	}
	
	/** */
	public List<Virologist> getVirologists() {
		return null;
	}
	
	/** */
	public void setNeighbours(List<Field> n) {
	}
	
	/** */
	public List<Field> getNeighbours() {
		return null;
	}
	
	/** */
	public void addVirologist(Virologist v) {
	}
	
	/** */
	public void removeVirologist(Virologist v) {
	}
}
