import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class Field {
	private List<Field> neigbours = new ArrayList<Field>();
	protected List<Virologist> virologists = new ArrayList<Virologist>();
	private String name;
	
	public Field(String _name) {
		name = _name;
	}
	
	public void interact(Virologist v) {
		
	}
	
	/** */
	public List<Virologist> getVirologists() {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".getVirologists()");
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
		return virologists;
	}
	
	/** */
	public void setNeighbours(List<Field> n) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".setNeighbours()");
		neigbours = n;
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** */
	public List<Field> getNeighbours() {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".getNeighbours()");
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
		return neigbours;
	}
	
	/** */
	public void addVirologist(Virologist v) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".addVirologist()");
		virologists.add(v);
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** */
	public void removeVirologist(Virologist v) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".removeVirologist()");
		virologists.remove(v);
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
}
