//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gear.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public abstract class Gear {
	/** */
	public abstract boolean specialEffect(Virologist v, Virologist att, Agent a);
	
	/** */
	public void onPickup(Virologist v) {
	}
	
	/** */
	public void onLoss(Virologist v) {
	}
}
