//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GeneticCode.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class GeneticCode {
	/** */
	private int requiredNucleotid;
	
	/** */
	private int requiredAminoacid;
	
	/** */
	public Agent Unnamed1;
	
	/** */
	public Laboratory Unnamed3;
	
	/** */
	public Agent make(Virologist v, int nuc, int acid) {
		return Unnamed1;
	}
}
