//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GeneticCode.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class GeneticCode {

	public String name;
	/** */
	protected int requiredNucleotid;

	/** */
	protected int requiredAminoacid;

	/** */
	public Agent agent;

	/** */
	public Laboratory Unnamed3;

	/** */
	public Agent make(Virologist v, int nuc, int acid) {

		main.increaseIndentation();

		if(requiredNucleotid > nuc || requiredAminoacid > acid) {
			System.out.println(main.printIndentation() + "Creation failed due to insufficient materials!" );

			main.decreaseIndentation();

			return null;
		}
		else {
			System.out.println(main.printIndentation() + "Creation succesful!");
			main.decreaseIndentation();

			v.removeAminoacid(requiredAminoacid);
			v.removeNucleotid(requiredNucleotid);

			return agent;
		}
	}
}
