//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gloves.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


import java.util.*;

/** */
public class Gloves extends Gear {
	/** */
	public boolean specialEffect(Virologist v, Virologist att, Agent a) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->specialEffect()");
		
		List<Virologist> l = new ArrayList<Virologist>();
		l.add(att);
		a.causeEffect(l, v);
		
		System.out.println(main.printIndentation() + "<-true");
		main.decreaseIndentation();
		return true;
	}
}
