//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gloves.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class Gloves extends Gear {
	/** */
	public boolean specialEffect(Virologist v, Virologist att, Agent a) {
		return false;
	}
}
