//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gloves.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


import java.util.*;

/** */
public class Gloves extends Gear {
	private String name;
	
	public Gloves(String _name) {
		name = _name;
	}
	
	/** */
	public boolean specialEffect(Virologist v, Virologist att, Agent a) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".specialEffect()");
		
		List<Virologist> l = new ArrayList<Virologist>();
		l.add(att);
		a.causeEffect(l, v);
		
		System.out.println(main.printIndentation() + "<-true");
		main.decreaseIndentation();
		return true;
	}
	
	/** */
	public void onPickup(Virologist v) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".onPickup()");
		v.addGear(this);
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** */
	public void onLoss(Virologist v) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".onLoss()");
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
}
