//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LabCoat.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** 
 * A védőköpeny felszerelést reprezentálja. 
 * Használatával 82,3%-os védelmet nyer a virológus az ágensek ellen. 
 * */

public class LabCoat extends Gear {
	private String name;
	
	/** 
	 * A konstruktor beállítja az objektum nevét, csak tesztelési célra.
	 * */
	
	public LabCoat(String _name) {
		name = _name;
	}
	
	/** 
	 * A védőfelszerelés speciális függvénye amely segítségével támadás esetén aktiválódik a felszerelés hatása a virológuson. 
	 * A virológust ért támadás esetén 82,3%-os eséllyel megvédi az ágens hatásától, 
	 * ilyenkor true értékkel tér vissza, egyébként false-al.
	 * */
	
	public boolean specialEffect(Virologist v, Virologist att, Agent a) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".specialEffect()");
		
		System.out.print(main.printIndentation() + "Does the labcoat protect the virologist? (y/n): ");
    	if(main.sc.next().charAt(0) == 'y') {
    		System.out.println(main.printIndentation() + "<-true");
    		main.decreaseIndentation();
    		return true;
    	}
    	System.out.println(main.printIndentation() + "<-false");
		main.decreaseIndentation();
		return false;
	}
	
	/** 
	 * A védőfelszerelések felvételénél kifejtik hatásukat a virológusra. A védőköpeny esetében nem csinál semmit.
	 * */
	
	public void onPickup(Virologist v) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".onPickup()");
		v.addGear(this);
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** 
	 * A védőfelszerelések elvesztésekor a virológus is elveszíti a felvételkor szerzett hatásokat. 
	 * A védőköpeny esetében nem csinál semmit.
	 * */
	
	public void onLoss(Virologist v) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".onLoss()");
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
}
