//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Laboratory.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class Laboratory extends Field {
	public GeneticCode geneticCode;
	
	public Laboratory(String _name) {
		super(_name);
	}
	
	/** */
	public void interact(Virologist v) {
	}
}
