//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Laboratory.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** 
 * Egy laboratórium mezőt reprezentál. 
 * A játékos ezen a mezőn tanulhatja meg a genetikus kódokat valamint állíthat elő ágenseket.
 * */

public class Laboratory extends Field {
	public GeneticCode geneticCode;

	/** 
	 * A konstruktor beállítja az objektum nevét, csak tesztelési célra.
	 * */
	
	public Laboratory(String _name) {
		super(_name);
	}

	/** 
	 * A laboratórium mezőn lévő játékos meghívhatja a mező interakciós függvényét. 
	 * Ez a függvény valósítja meg, hogy a virológus megtanulja a laboratórium genetikus kódját 
	 * - meghívja a virológus addGeneticCode függvényét. Ha már ismeri a virológus a kódot, 
	 * akkor nem történik változás.
	 * */
	
	public void interact(Virologist v) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".interact()");

		v.addGeneticCode(geneticCode);

		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();

	}

	/** 
	 * Beállítja a laboratóriumban található genetikai kódot.
	 * */
	
	public void addGeneticCode(GeneticCode gc) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".addGeneticCode()");

		geneticCode = gc;

		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
}
