//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : P.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class P extends GeneticCode {
    public P() {requiredNucleotid = 3; requiredAminoacid = 3; agent = new Paralisis("p"); name = "P";}
}
