//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : P.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class P extends GeneticCode {
	
}
