import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Paralisis.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** 
 * A paralízis olyan ágens, amely megbénít, így amíg az ágens hatása tart, az áldozat nem tud semmit csinálni (lebénul).
 * */

public class Paralisis extends Agent {
	private String name;
	
	/** 
 	* A konstruktor beállítja az objektum nevét, csak tesztelési célra.
 	* */
	
	public Paralisis(String _name) {
		name = _name;
	}
	
	/** 
	 * A függvény a paraméterként kapott virológusokra megpróbálja az ágenst rákenni és kiváltani a hatását: 
	 * megbénítani a virológusokat, ez azt eredményezi, hogy amíg az ágens hatása tart az áldozat nem tud semmit csinálni (lebénul).
	 * */
	
	public void causeEffect(List<Virologist> targets, Virologist source) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".causeEffect()");
		
		for(int i=0;i<targets.size();i++) {
			Virologist t = targets.get(i);
			if(t.infect(this, source)) {
				t.setParalyzed(true);
			}
		}
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** 
	 * A Steppable interfészből implementált step() függvény. Az idő múlásának hatását valósítja meg.
	 * */
	
	public void step() {
	}
}
