//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shelter.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class Shelter extends Field {
	public Gear gear;
	
	public Shelter(String _name) {
		super(_name);
	}
	
	/** */
	public void interact(Virologist v) {
	}
}
