//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Steppable.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public interface Steppable {
	/** */
	public void step();
}
