//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Storage.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class Storage extends Field {
	private int nucleotidCount;
	private int aminoacidCount;
	
	public Storage(String _name) {
		super(_name);
	}
	
	/** */
	public void interact(Virologist v) {
	}
}
