//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Storage.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class Storage extends Field {
	private int nucleotidCount;
	private int aminoacidCount;
	
	public Storage(String _name) {
		super(_name);
	}
	
	public void setMaterials(int nucleotid, int aminoacid) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".setMaterials()");
		this.nucleotidCount = nucleotid;
		this.aminoacidCount = aminoacid;
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** */
	public void interact(Virologist v) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".interact()");
		v.addAminoacid(aminoacidCount);
		v.addNucleotid(nucleotidCount);
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
}
