//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Storage.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** 
 * Egy raktár mezőt reprezentál. A játékos ezen a mezőn anyagokat gyűjthet 
 * melyeket az ágensek előállításához használhat fel.
 * */

public class Storage extends Field {
	private int nucleotidCount;
	private int aminoacidCount;
	
	/** 
	 * A konstruktor beállítja az objektum nevét, csak tesztelési célra.
	 * */
	
	public Storage(String _name) {
		super(_name);
	}
	
	/** 
	 * Beállítja a raktárban található aminosav és nukleotid darabszámát.
	 * */
	
	public void setMaterials(int nucleotid, int aminoacid) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".setMaterials()");
		this.nucleotidCount = nucleotid;
		this.aminoacidCount = aminoacid;
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** 
	 * A raktár mezőn lévő játékos meghívhatja a mező interakciós függvényét. 
	 * Ez a függvény valósítja meg a játékos anyagfelszedését. 
	 * A raktárban található anyagok a játékoshoz kerülnek azáltal, 
	 * hogy meghívja a virológus setNucleotidCount és setAminoacidCount függvényeket 
	 * amelyek segítségével hozzáadódik a virológus anyagkészletéhez a raktárban található mennyiség.
	 * */
	
	public void interact(Virologist v) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->" + name + ".interact()");
		v.addAminoacid(aminoacidCount);
		v.addNucleotid(nucleotidCount);
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
}
