//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : V.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




/** */
public class V extends GeneticCode {
    public V() {requiredNucleotid = 1; requiredAminoacid = 1; agent = new Vaccine("v"); name = "V";}
}
