import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Virologist.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


import java.util.*;

/** */
class Virologist implements Steppable {
	private int nucleotidCount;
	private int aminoacidCount;
	private int maxAgents;
	private int maxMaterials;
	private boolean paralyzed;
	private boolean chorea;
	private boolean vaccinated;
	private List<Agent> agents = new ArrayList<Agent>();
	private List<GeneticCode> geneticCodes = new ArrayList<GeneticCode>();
	public Field field;
	private List<Gear> gears = new ArrayList<Gear>();
	
	/** */
	public void createAgent(String agent) {
	}
	
	/** */
	public void move(Field field) {
	}
	
	/** */
	public void useAgent(List<Virologist> virologists, Agent agent) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->useAgent()");
		
		agent.causeEffect(virologists, this);
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** */
	public void setMaxMaterials(int n) {
	}
	
	/** */
	public void setMaxAgents(int n) {
	}
	
	/** */
	public int addNucleotid() {
		return 0;
	}
	
	/** */
	public void removeNucleotid(int n) {
	}
	
	/** */
	public void addAminoacid(int n) {
	}
	
	/** */
	public int removeAminoacid() {
		return 0;
	}
	
	/** */
	public void addGeneticCode(GeneticCode g) {
	}
	
	/** */
	public void forgetGeneticCodes() {
	}
	
	/** */
	public void addGear(Gear g) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->addGear()");
		if(gears.size()<3)
			gears.add(g);
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** */
	public boolean infect(Agent a, Virologist att) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->infect()");
		
		if(!vaccinated) {
			for(int i=0;i<gears.size();i++) {
				if(gears.get(i).specialEffect(this, att, a)) {
					System.out.println(main.printIndentation() + "<-false");
					main.decreaseIndentation();
					return false;
				}
			}
			System.out.println(main.printIndentation() + "<-true");
			main.decreaseIndentation();
			return true;
		}
		System.out.println(main.printIndentation() + "<-false");
		main.decreaseIndentation();
		return false;
	}
	
	/** */
	public void stealFrom(Virologist target) {
	}
	
	/** */
	public void steal(Virologist attacker) {
	}
	
	/** */
	public void setField(Field f) {
	}
	
	/** */
	public void setVaccinated(boolean b) {
	}
	
	/** */
	public void setParalyzed(boolean b) {
	}
	
	/** */
	public void setChorea(boolean b) {
		main.increaseIndentation();
		System.out.println(main.printIndentation() + "->setChorea()");
		System.out.println(main.printIndentation() + "<-");
		main.decreaseIndentation();
	}
	
	/** */
	public void fieldInteract() {
	}
	
	/** */
	public void step() {
	}
}
